const { ROLES } = require("./roles");

const PERMISSIONS = Object.freeze({
  DASHBOARD_VIEW: "dashboard:view",
  CUSTOMERS_VIEW: "customers:view",
  CUSTOMERS_CREATE: "customers:create",
  CUSTOMERS_EDIT: "customers:edit",
  BUILDINGS_VIEW: "buildings:view",
  BUILDINGS_CREATE: "buildings:create",
  BUILDINGS_EDIT: "buildings:edit",
  ASSETS_VIEW: "assets:view",
  ASSETS_CREATE: "assets:create",
  ASSETS_EDIT: "assets:edit",
  ASSETS_ADMIN: "assets:admin",
  WORK_ORDERS_VIEW: "work_orders:view",
  WORK_ORDERS_CREATE: "work_orders:create",
  WORK_ORDERS_EDIT: "work_orders:edit",
  WORK_ORDERS_ASSIGN: "work_orders:assign",
  SETTINGS_ADMIN: "settings:admin"
});

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.CEO]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.BUILDINGS_VIEW,
    PERMISSIONS.BUILDINGS_CREATE,
    PERMISSIONS.BUILDINGS_EDIT,
    PERMISSIONS.ASSETS_VIEW,
    PERMISSIONS.ASSETS_CREATE,
    PERMISSIONS.ASSETS_EDIT,
    PERMISSIONS.ASSETS_ADMIN,
    PERMISSIONS.WORK_ORDERS_VIEW,
    PERMISSIONS.WORK_ORDERS_CREATE,
    PERMISSIONS.WORK_ORDERS_EDIT,
    PERMISSIONS.WORK_ORDERS_ASSIGN
  ],
  [ROLES.OPERATIONS_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.BUILDINGS_VIEW,
    PERMISSIONS.BUILDINGS_CREATE,
    PERMISSIONS.BUILDINGS_EDIT,
    PERMISSIONS.ASSETS_VIEW,
    PERMISSIONS.ASSETS_CREATE,
    PERMISSIONS.ASSETS_EDIT,
    PERMISSIONS.ASSETS_ADMIN,
    PERMISSIONS.WORK_ORDERS_VIEW,
    PERMISSIONS.WORK_ORDERS_CREATE,
    PERMISSIONS.WORK_ORDERS_EDIT,
    PERMISSIONS.WORK_ORDERS_ASSIGN
  ],
  [ROLES.OFFICE_ADMINISTRATOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.BUILDINGS_VIEW,
    PERMISSIONS.BUILDINGS_CREATE,
    PERMISSIONS.BUILDINGS_EDIT,
    PERMISSIONS.ASSETS_VIEW,
    PERMISSIONS.ASSETS_CREATE,
    PERMISSIONS.ASSETS_EDIT,
    PERMISSIONS.ASSETS_ADMIN,
    PERMISSIONS.WORK_ORDERS_VIEW,
    PERMISSIONS.WORK_ORDERS_CREATE,
    PERMISSIONS.WORK_ORDERS_EDIT,
    PERMISSIONS.WORK_ORDERS_ASSIGN
  ],
  [ROLES.SALES_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.BUILDINGS_VIEW,
    PERMISSIONS.ASSETS_VIEW,
    PERMISSIONS.WORK_ORDERS_VIEW
  ],
  [ROLES.ENGINEER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.BUILDINGS_VIEW,
    PERMISSIONS.ASSETS_VIEW,
    PERMISSIONS.ASSETS_CREATE,
    PERMISSIONS.ASSETS_EDIT,
    PERMISSIONS.WORK_ORDERS_VIEW,
    PERMISSIONS.WORK_ORDERS_CREATE,
    PERMISSIONS.WORK_ORDERS_EDIT
  ],
  [ROLES.TECHNICIAN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.BUILDINGS_VIEW,
    PERMISSIONS.ASSETS_VIEW,
    PERMISSIONS.ASSETS_EDIT,
    PERMISSIONS.WORK_ORDERS_VIEW,
    PERMISSIONS.WORK_ORDERS_EDIT
  ],
  [ROLES.SUBCONTRACTOR]: [
    PERMISSIONS.DASHBOARD_VIEW
  ],
  [ROLES.CUSTOMER]: [
    PERMISSIONS.DASHBOARD_VIEW
  ],
  [ROLES.AUDITOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.BUILDINGS_VIEW,
    PERMISSIONS.ASSETS_VIEW,
    PERMISSIONS.WORK_ORDERS_VIEW
  ]
});

function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}

function hasPermission(user, permission) {
  return getPermissionsForRole(user?.role).includes(permission);
}

module.exports = {
  PERMISSIONS,
  getPermissionsForRole,
  hasPermission
};
