const { ROLES } = require("./roles");

const PERMISSIONS = Object.freeze({
  DASHBOARD_VIEW: "dashboard:view",
  CUSTOMERS_VIEW: "customers:view",
  CUSTOMERS_CREATE: "customers:create",
  CUSTOMERS_EDIT: "customers:edit",
  BUILDINGS_VIEW: "buildings:view",
  BUILDINGS_CREATE: "buildings:create",
  BUILDINGS_EDIT: "buildings:edit",
  SETTINGS_ADMIN: "settings:admin"
});

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.CEO]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.BUILDINGS_VIEW,
    PERMISSIONS.BUILDINGS_CREATE,
    PERMISSIONS.BUILDINGS_EDIT
  ],
  [ROLES.OPERATIONS_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.BUILDINGS_VIEW,
    PERMISSIONS.BUILDINGS_CREATE,
    PERMISSIONS.BUILDINGS_EDIT
  ],
  [ROLES.OFFICE_ADMINISTRATOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.BUILDINGS_VIEW,
    PERMISSIONS.BUILDINGS_CREATE,
    PERMISSIONS.BUILDINGS_EDIT
  ],
  [ROLES.SALES_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.BUILDINGS_VIEW
  ],
  [ROLES.ENGINEER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.BUILDINGS_VIEW
  ],
  [ROLES.TECHNICIAN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.BUILDINGS_VIEW
  ],
  [ROLES.SUBCONTRACTOR]: [
    PERMISSIONS.DASHBOARD_VIEW
  ],
  [ROLES.CUSTOMER]: [
    PERMISSIONS.DASHBOARD_VIEW
  ],
  [ROLES.AUDITOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.BUILDINGS_VIEW
  ]
});

function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}

function hasPermission(user, permission) {
  return getPermissionsForRole(user?.role).includes(permission);
}

module.exports = {
  PERMISSIONS,
  getPermissionsForRole,
  hasPermission
};
